import type { AiScenarioDraft, Scenario, SimulationBlockId } from "@csm-sim/contracts";
import { randomUUID } from "node:crypto";

export interface AiDraftRequest {
  prompt: string;
  purpose: AiScenarioDraft["purpose"];
  allowedBlocks: SimulationBlockId[];
  limits: {
    maxObjects: number;
    maxDurationSeconds: number;
    externalProviderAllowed: boolean;
  };
  providerPreference?: "openai" | "codex" | "local" | "mock" | "auto";
}

const prohibitedPatterns = [
  /target/i,
  /nav[aá]d[eě]n[ií]/i,
  /weapon|zbra[nň]/i,
  /attack|útok/i,
  /use of force|použit[ií] s[ií]ly/i,
  /mission planning|bojov[aá] mise/i,
  /avoid detection|vyh(y|ý)b[aá]n[ií] detekci/i
];

export function classifyPrompt(prompt: string): { allowed: boolean; reasons: string[] } {
  const hits = prohibitedPatterns.filter((pattern) => pattern.test(prompt));
  if (hits.length > 0) {
    return {
      allowed: false,
      reasons: ["Požadavek zasahuje do zakázaného targeting/navádění/zbraňového nebo bojového workflow."]
    };
  }
  return {
    allowed: true,
    reasons: ["Synthetic COP test scenario request."]
  };
}

export function createMockScenarioDraft(request: AiDraftRequest): AiScenarioDraft {
  const policy = classifyPrompt(request.prompt);
  const selectedBlocks = request.allowedBlocks.slice(0, 3);
  const durationSeconds = Math.min(request.limits.maxDurationSeconds, 900);
  const objectBudget = Math.max(1, Math.min(request.limits.maxObjects, 120));
  const perBlock = Math.max(1, Math.floor(objectBudget / Math.max(1, selectedBlocks.length)));

  const scenarioPatch: Partial<Scenario> = policy.allowed
    ? {
        name: `AI draft: ${request.purpose.toLowerCase().replaceAll("_", " ")}`,
        description: "Synthetic scenario draft generated by mock AI provider for COP ingest testing.",
        area: {
          type: "BBOX",
          bbox: [14.0, 49.8, 15.0, 50.3]
        },
        durationSeconds,
        seed: 123456,
        blocks: selectedBlocks.map((blockId) => ({
          blockId,
          enabled: true,
          objectCount: perBlock,
          updateRateHz: request.purpose === "LOAD_TEST" ? 2 : 1,
          patterns: blockId === "air-sim-uav" ? ["LOITER", "SURVEY"] : ["DIRECT"]
        })),
        faults:
          request.purpose === "DEGRADED_CONNECTIVITY"
            ? [
                {
                  type: "SOURCE_OUTAGE",
                  targetBlockId: selectedBlocks[0] ?? "air-sim-uav",
                  startAtSecond: 300,
                  durationSeconds: 120,
                  parameters: { reconnectBurst: true }
                }
              ]
            : []
      }
    : {};

  return {
    draftId: randomUUID(),
    title: policy.allowed ? "Synthetic COP scenario draft" : "Rejected scenario draft",
    purpose: request.purpose,
    safetyScope: "SYNTHETIC_COP_TEST_ONLY",
    provider: "mock",
    scenarioPatch,
    expectedObservations: policy.allowed
      ? ["Schema validation passes.", "All generated events carry SYNTHETIC marking.", "Publisher can run in dry-run mode."]
      : [],
    policyCheck: policy,
    prohibitedContentCheck: {
      targeting: false,
      weaponGuidance: false,
      realOperationalAdvice: false,
      useOfForceRecommendation: false,
      attackOptimization: false
    },
    validation: {
      schemaValid: policy.allowed,
      issues: policy.allowed ? [] : [{ message: policy.reasons[0] }]
    },
    explanation: policy.allowed
      ? "Draft is limited to synthetic COP test data and requires human review before it can be accepted."
      : "Prompt was rejected by AI guardrails.",
    audit: {
      requestId: randomUUID(),
      createdAt: new Date().toISOString(),
      humanReviewStatus: "PENDING"
    }
  };
}

export const aiProviders = [
  { id: "mock", enabled: true, external: false, healthy: true },
  { id: "local", enabled: false, external: false, healthy: false },
  { id: "openai", enabled: false, external: true, healthy: false },
  { id: "codex", enabled: false, external: true, healthy: false }
];
