FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        osmium-tool \
        python3 \
        python3-pyproj \
        python3-shapely \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work
