#!/usr/bin/env bash
set -euo pipefail

cd /srv/sim

if [ ! -d .git ]; then
  git clone https://github.com/voldzi/delta_acr_sim.git .
else
  git pull --ff-only
fi

cat > .env <<'ENV'
SIM_WEB_PORT=5020
API_PORT=4000
SIM_PUBLISHER_MODE=DRY_RUN
SIM_SOURCE_SYSTEM_ID=sim-air-situation-001
SIM_ADAPTER_VERSION=0.1.0
SIM_DATA_DIR=/data
MAIN_COP_BASE_URL=http://sim-api:4000/mock-cop
MAIN_COP_BEARER_TOKEN=dev-lab-token
EXTERNAL_AI_ALLOWED=false
FLIGHT_DATA_ENABLED_SOURCES=adsb_lol
FLIGHT_DATA_DEFAULT_LAT=50.1008
FLIGHT_DATA_DEFAULT_LON=14.2632
FLIGHT_DATA_DEFAULT_RADIUS_NM=120
FLIGHT_DATA_CACHE_TTL_SECONDS=10
FLIGHT_DATA_STALE_IF_ERROR_SECONDS=60
FLIGHT_DATA_CACHE_MAX_ENTRIES=512
FLIGHT_DATA_STALE_AFTER_SECONDS=120
FLIGHT_DATA_REQUEST_TIMEOUT_MS=8000
LOCAL_ADSB_AIRCRAFT_JSON_URLS=
OURAIRPORTS_ENABLED=true
OURAIRPORTS_COUNTRIES=CZ,SK,AT,DE,PL,HU
OURAIRPORTS_CACHE_TTL_SECONDS=86400
SITUATION_DATA_ENABLED_SOURCES=open_meteo,aviation_weather,ctu_nettest,pid_gtfs_rt,safety_data
SITUATION_DATA_DEFAULT_BBOX=13.85,49.65,15.35,50.45
SITUATION_DATA_CACHE_TTL_SECONDS=30
SITUATION_DATA_STALE_IF_ERROR_SECONDS=1800
SITUATION_DATA_CACHE_MAX_ENTRIES=10000
SITUATION_DATA_BBOX_CACHE_PADDING_DEGREES=0.18
SITUATION_DATA_OPEN_METEO_CACHE_TTL_SECONDS=600
SITUATION_DATA_OPEN_METEO_GRID_DEGREES=0.05
SITUATION_DATA_OVERPASS_CACHE_TTL_SECONDS=21600
SITUATION_DATA_SAFETY_CACHE_TTL_SECONDS=300
SITUATION_DATA_AVIATION_WEATHER_CACHE_TTL_SECONDS=600
SITUATION_DATA_ARDOS_CACHE_TTL_SECONDS=15
SITUATION_DATA_STALE_AFTER_SECONDS=900
SITUATION_DATA_REQUEST_TIMEOUT_MS=8000
OPEN_METEO_BASE_URL=https://api.open-meteo.com
OVERPASS_BASE_URL=https://overpass-api.de/api/interpreter
OVERPASS_MAX_BBOX_DEGREES=1.6
CTU_NETTEST_URL=https://nettest.ctu.gov.cz/RMBTStatisticServer/export/nettest-opendata_hours-048.zip
PID_GTFS_RT_VEHICLE_POSITIONS_URL=https://api.golemio.cz/v2/vehiclepositions/gtfsrt/vehicle_positions.pb
SAFETY_DATA_BASE_URL=http://safety-data-api:4030
AVIATION_WEATHER_BASE_URL=https://aviationweather.gov
ARDOS_PARTNER_BASE_URL=
ARDOS_PARTNER_TOKEN=
ENV

docker compose up -d --build
docker compose ps
curl -fsS http://localhost:5020/health/live
curl -fsS http://localhost:5020/flight-data/health/ready
curl -fsS http://localhost:5020/situation-data/health/ready
curl -fsS 'http://localhost:5020/situation-data/api/v1/cop/features?layers=weather,mobile,traffic,warnings,flood&limit=20' >/dev/null
