#!/usr/bin/env bash
set -euo pipefail

cd /srv/sim

if [ ! -d .git ]; then
  : "${SIM_GIT_REPOSITORY_URL:?Set SIM_GIT_REPOSITORY_URL to the SIM repository clone URL.}"
  git clone "$SIM_GIT_REPOSITORY_URL" .
else
  git pull --ff-only
fi

existing_value() {
  local key="$1"
  if [ -f .env ]; then
    grep -E "^${key}=" .env | tail -n 1 | cut -d= -f2- || true
  fi
}

generate_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    python3 - <<'PY'
import secrets
print(secrets.token_hex(32))
PY
  fi
}

wait_for_http() {
  local url="$1"
  local label="$2"
  local attempts="${3:-30}"
  local delay_seconds="${4:-1}"

  for attempt in $(seq 1 "$attempts"); do
    if curl -fsS "$url" >/dev/null 2>&1; then
      return 0
    fi
    echo "Waiting for ${label} (${attempt}/${attempts})..."
    sleep "$delay_seconds"
  done

  echo "Timed out waiting for ${label}: ${url}" >&2
  curl -fsS "$url" >/dev/null
}

wait_for_container_healthy() {
  local container="$1"
  local label="$2"
  local attempts="${3:-60}"
  local delay_seconds="${4:-1}"
  local status=""

  for attempt in $(seq 1 "$attempts"); do
    status="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$container" 2>/dev/null || true)"
    if [ "$status" = "healthy" ]; then
      return 0
    fi
    echo "Waiting for ${label} (${attempt}/${attempts}); status=${status:-unknown}..."
    sleep "$delay_seconds"
  done

  echo "Timed out waiting for ${label}; status=${status:-unknown}" >&2
  docker inspect "$container" >/dev/null
  return 1
}

SIM_API_ADMIN_TOKEN_VALUE="${SIM_API_ADMIN_TOKEN:-$(existing_value SIM_API_ADMIN_TOKEN)}"
if [ -z "$SIM_API_ADMIN_TOKEN_VALUE" ]; then
  SIM_API_ADMIN_TOKEN_VALUE="$(generate_secret)"
fi

OSM_POSTGIS_DB_VALUE="${OSM_POSTGIS_DB:-$(existing_value OSM_POSTGIS_DB)}"
OSM_POSTGIS_DB_VALUE="${OSM_POSTGIS_DB_VALUE:-sim_osm}"
OSM_POSTGIS_USER_VALUE="${OSM_POSTGIS_USER:-$(existing_value OSM_POSTGIS_USER)}"
OSM_POSTGIS_USER_VALUE="${OSM_POSTGIS_USER_VALUE:-sim_osm}"
OSM_POSTGIS_PASSWORD_VALUE="${OSM_POSTGIS_PASSWORD:-$(existing_value OSM_POSTGIS_PASSWORD)}"
OSM_POSTGIS_BACKEND_VALUE="${OSM_POSTGIS_BACKEND:-$(existing_value OSM_POSTGIS_BACKEND)}"
OSM_POSTGIS_DATABASE_URL_VALUE="${OSM_POSTGIS_DATABASE_URL:-$(existing_value OSM_POSTGIS_DATABASE_URL)}"
if [ -n "$OSM_POSTGIS_DATABASE_URL_VALUE" ] && [ -z "$OSM_POSTGIS_BACKEND_VALUE" ]; then
  OSM_POSTGIS_BACKEND_VALUE="patroni-postgis"
fi
OSM_POSTGIS_TABLE_VALUE="${OSM_POSTGIS_TABLE:-$(existing_value OSM_POSTGIS_TABLE)}"
OSM_POSTGIS_TABLE_VALUE="${OSM_POSTGIS_TABLE_VALUE:-public.osm_poi}"
OSM_POSTGIS_ADMIN_BOUNDARY_TABLE_VALUE="${OSM_POSTGIS_ADMIN_BOUNDARY_TABLE:-$(existing_value OSM_POSTGIS_ADMIN_BOUNDARY_TABLE)}"
OSM_POSTGIS_ADMIN_BOUNDARY_TABLE_VALUE="${OSM_POSTGIS_ADMIN_BOUNDARY_TABLE_VALUE:-public.osm_admin_boundary}"
SAFETY_DATA_ADMIN_BOUNDARY_DATABASE_URL_VALUE="${SAFETY_DATA_ADMIN_BOUNDARY_DATABASE_URL:-$(existing_value SAFETY_DATA_ADMIN_BOUNDARY_DATABASE_URL)}"
SAFETY_DATA_ADMIN_BOUNDARY_DATABASE_URL_VALUE="${SAFETY_DATA_ADMIN_BOUNDARY_DATABASE_URL_VALUE:-$OSM_POSTGIS_DATABASE_URL_VALUE}"
SAFETY_DATA_ADMIN_BOUNDARY_TABLE_VALUE="${SAFETY_DATA_ADMIN_BOUNDARY_TABLE:-$(existing_value SAFETY_DATA_ADMIN_BOUNDARY_TABLE)}"
SAFETY_DATA_ADMIN_BOUNDARY_TABLE_VALUE="${SAFETY_DATA_ADMIN_BOUNDARY_TABLE_VALUE:-public.osm_admin_boundary}"
SAFETY_DATA_ADMIN_BOUNDARY_CACHE_TTL_SECONDS_VALUE="${SAFETY_DATA_ADMIN_BOUNDARY_CACHE_TTL_SECONDS:-$(existing_value SAFETY_DATA_ADMIN_BOUNDARY_CACHE_TTL_SECONDS)}"
SAFETY_DATA_ADMIN_BOUNDARY_CACHE_TTL_SECONDS_VALUE="${SAFETY_DATA_ADMIN_BOUNDARY_CACHE_TTL_SECONDS_VALUE:-86400}"
MOBILE_COVERAGE_MODEL_VERSION_VALUE="${MOBILE_COVERAGE_MODEL_VERSION:-$(existing_value MOBILE_COVERAGE_MODEL_VERSION)}"
MOBILE_COVERAGE_MODEL_VERSION_VALUE="${MOBILE_COVERAGE_MODEL_VERSION_VALUE:-coverage-v1}"
MOBILE_COVERAGE_DEM_SOURCE_VALUE="${MOBILE_COVERAGE_DEM_SOURCE:-$(existing_value MOBILE_COVERAGE_DEM_SOURCE)}"
MOBILE_COVERAGE_DEM_SOURCE_VALUE="${MOBILE_COVERAGE_DEM_SOURCE_VALUE:-not-used-phase-1}"
MOBILE_COVERAGE_TERRAIN_AWARE_VALUE="${MOBILE_COVERAGE_TERRAIN_AWARE:-$(existing_value MOBILE_COVERAGE_TERRAIN_AWARE)}"
MOBILE_COVERAGE_TERRAIN_AWARE_VALUE="${MOBILE_COVERAGE_TERRAIN_AWARE_VALUE:-false}"
DEM_ENABLED_VALUE="${DEM_ENABLED:-$(existing_value DEM_ENABLED)}"
DEM_ENABLED_VALUE="${DEM_ENABLED_VALUE:-false}"
DEM_BBOX_VALUE="${DEM_BBOX:-$(existing_value DEM_BBOX)}"
DEM_BBOX_VALUE="${DEM_BBOX_VALUE:-11.8,48.5,19.2,51.2}"
DEM_DATASET_ID_VALUE="${DEM_DATASET_ID:-$(existing_value DEM_DATASET_ID)}"
DEM_DATASET_ID_VALUE="${DEM_DATASET_ID_VALUE:-copernicus-glo30-cz}"
DEM_POSTGIS_DATABASE_URL_VALUE="${DEM_POSTGIS_DATABASE_URL:-$(existing_value DEM_POSTGIS_DATABASE_URL)}"
DEM_LOCAL_CACHE_HOST_DIR_VALUE="${DEM_LOCAL_CACHE_HOST_DIR:-$(existing_value DEM_LOCAL_CACHE_HOST_DIR)}"
DEM_LOCAL_CACHE_HOST_DIR_VALUE="${DEM_LOCAL_CACHE_HOST_DIR_VALUE:-./data/dem-cache/copernicus-glo30}"
DEM_LOCAL_CACHE_DIR_VALUE="${DEM_LOCAL_CACHE_DIR:-$(existing_value DEM_LOCAL_CACHE_DIR)}"
DEM_LOCAL_CACHE_DIR_VALUE="${DEM_LOCAL_CACHE_DIR_VALUE:-/dem-cache/copernicus-glo30}"
DEM_SEAWEEDFS_ENABLED_VALUE="${DEM_SEAWEEDFS_ENABLED:-$(existing_value DEM_SEAWEEDFS_ENABLED)}"
DEM_SEAWEEDFS_ENABLED_VALUE="${DEM_SEAWEEDFS_ENABLED_VALUE:-false}"
DEM_SEAWEEDFS_S3_ENDPOINT_VALUE="${DEM_SEAWEEDFS_S3_ENDPOINT:-$(existing_value DEM_SEAWEEDFS_S3_ENDPOINT)}"
DEM_SEAWEEDFS_BUCKET_VALUE="${DEM_SEAWEEDFS_BUCKET:-$(existing_value DEM_SEAWEEDFS_BUCKET)}"
DEM_SEAWEEDFS_BUCKET_VALUE="${DEM_SEAWEEDFS_BUCKET_VALUE:-sim-dem}"
DEM_SEAWEEDFS_PREFIX_VALUE="${DEM_SEAWEEDFS_PREFIX:-$(existing_value DEM_SEAWEEDFS_PREFIX)}"
DEM_SEAWEEDFS_PREFIX_VALUE="${DEM_SEAWEEDFS_PREFIX_VALUE:-copernicus-glo30/2021}"
DEM_SEAWEEDFS_ACCESS_KEY_ID_VALUE="${DEM_SEAWEEDFS_ACCESS_KEY_ID:-$(existing_value DEM_SEAWEEDFS_ACCESS_KEY_ID)}"
DEM_SEAWEEDFS_SECRET_ACCESS_KEY_VALUE="${DEM_SEAWEEDFS_SECRET_ACCESS_KEY:-$(existing_value DEM_SEAWEEDFS_SECRET_ACCESS_KEY)}"
SIM_OPERATIONAL_ALERT_WEBHOOK_URL_VALUE="${SIM_OPERATIONAL_ALERT_WEBHOOK_URL:-$(existing_value SIM_OPERATIONAL_ALERT_WEBHOOK_URL)}"
SIM_OPERATIONAL_ALERT_ENVIRONMENT_VALUE="${SIM_OPERATIONAL_ALERT_ENVIRONMENT:-$(existing_value SIM_OPERATIONAL_ALERT_ENVIRONMENT)}"
SIM_OPERATIONAL_ALERT_ENVIRONMENT_VALUE="${SIM_OPERATIONAL_ALERT_ENVIRONMENT_VALUE:-docker-home}"
SIM_OPERATIONAL_BASE_URL_VALUE="${SIM_OPERATIONAL_BASE_URL:-$(existing_value SIM_OPERATIONAL_BASE_URL)}"
SIM_OPERATIONAL_BASE_URL_VALUE="${SIM_OPERATIONAL_BASE_URL_VALUE:-http://127.0.0.1:5020}"
SIM_OPERATIONAL_API_TOKEN_VALUE="${SIM_OPERATIONAL_API_TOKEN:-$(existing_value SIM_OPERATIONAL_API_TOKEN)}"
SIM_OPERATIONAL_CHECK_BBOX_VALUE="${SIM_OPERATIONAL_CHECK_BBOX:-$(existing_value SIM_OPERATIONAL_CHECK_BBOX)}"
SIM_OPERATIONAL_CHECK_BBOX_VALUE="${SIM_OPERATIONAL_CHECK_BBOX_VALUE:-11.8,48.5,19.2,51.2}"
SIM_OPERATIONAL_BOUNDARY_BBOX_VALUE="${SIM_OPERATIONAL_BOUNDARY_BBOX:-$(existing_value SIM_OPERATIONAL_BOUNDARY_BBOX)}"
SIM_OPERATIONAL_BOUNDARY_BBOX_VALUE="${SIM_OPERATIONAL_BOUNDARY_BBOX_VALUE:-12,48,19,51}"
SIM_OPERATIONAL_TERRAIN_BBOX_VALUE="${SIM_OPERATIONAL_TERRAIN_BBOX:-$(existing_value SIM_OPERATIONAL_TERRAIN_BBOX)}"
SIM_OPERATIONAL_TERRAIN_BBOX_VALUE="${SIM_OPERATIONAL_TERRAIN_BBOX_VALUE:-13.95,50.55,14.08,50.65}"
SIM_OPERATIONAL_EXPECTED_DEM_SOURCE_VALUE="${SIM_OPERATIONAL_EXPECTED_DEM_SOURCE:-$(existing_value SIM_OPERATIONAL_EXPECTED_DEM_SOURCE)}"
SIM_OPERATIONAL_EXPECTED_DEM_SOURCE_VALUE="${SIM_OPERATIONAL_EXPECTED_DEM_SOURCE_VALUE:-copernicus-glo30-cz}"
SIM_OPERATIONAL_EXPECTED_MOBILE_MODEL_VERSION_VALUE="${SIM_OPERATIONAL_EXPECTED_MOBILE_MODEL_VERSION:-$(existing_value SIM_OPERATIONAL_EXPECTED_MOBILE_MODEL_VERSION)}"
SIM_OPERATIONAL_EXPECTED_MOBILE_MODEL_VERSION_VALUE="${SIM_OPERATIONAL_EXPECTED_MOBILE_MODEL_VERSION_VALUE:-coverage-v2-terrain}"
SIM_OPERATIONAL_REQUIRE_DEM_VALUE="${SIM_OPERATIONAL_REQUIRE_DEM:-$(existing_value SIM_OPERATIONAL_REQUIRE_DEM)}"
SIM_OPERATIONAL_REQUIRE_DEM_VALUE="${SIM_OPERATIONAL_REQUIRE_DEM_VALUE:-true}"
SIM_OPERATIONAL_REQUIRE_TERRAIN_AWARE_VALUE="${SIM_OPERATIONAL_REQUIRE_TERRAIN_AWARE:-$(existing_value SIM_OPERATIONAL_REQUIRE_TERRAIN_AWARE)}"
SIM_OPERATIONAL_REQUIRE_TERRAIN_AWARE_VALUE="${SIM_OPERATIONAL_REQUIRE_TERRAIN_AWARE_VALUE:-true}"
SIM_OPERATIONAL_ALERT_ON_RECOVERY_VALUE="${SIM_OPERATIONAL_ALERT_ON_RECOVERY:-$(existing_value SIM_OPERATIONAL_ALERT_ON_RECOVERY)}"
SIM_OPERATIONAL_ALERT_ON_RECOVERY_VALUE="${SIM_OPERATIONAL_ALERT_ON_RECOVERY_VALUE:-true}"
SIM_OPERATIONAL_ALERT_EVERY_FAILURE_VALUE="${SIM_OPERATIONAL_ALERT_EVERY_FAILURE:-$(existing_value SIM_OPERATIONAL_ALERT_EVERY_FAILURE)}"
SIM_OPERATIONAL_ALERT_EVERY_FAILURE_VALUE="${SIM_OPERATIONAL_ALERT_EVERY_FAILURE_VALUE:-false}"
SIM_OPERATIONAL_SLO_AVAILABILITY_TARGET_VALUE="${SIM_OPERATIONAL_SLO_AVAILABILITY_TARGET:-$(existing_value SIM_OPERATIONAL_SLO_AVAILABILITY_TARGET)}"
SIM_OPERATIONAL_SLO_AVAILABILITY_TARGET_VALUE="${SIM_OPERATIONAL_SLO_AVAILABILITY_TARGET_VALUE:-0.995}"
SIM_OPERATIONAL_CHECK_INTERVAL_SECONDS_VALUE="${SIM_OPERATIONAL_CHECK_INTERVAL_SECONDS:-$(existing_value SIM_OPERATIONAL_CHECK_INTERVAL_SECONDS)}"
SIM_OPERATIONAL_CHECK_INTERVAL_SECONDS_VALUE="${SIM_OPERATIONAL_CHECK_INTERVAL_SECONDS_VALUE:-300}"
SIM_OPERATIONAL_SLO_MAX_LIVE_LATENCY_MS_VALUE="${SIM_OPERATIONAL_SLO_MAX_LIVE_LATENCY_MS:-$(existing_value SIM_OPERATIONAL_SLO_MAX_LIVE_LATENCY_MS)}"
SIM_OPERATIONAL_SLO_MAX_LIVE_LATENCY_MS_VALUE="${SIM_OPERATIONAL_SLO_MAX_LIVE_LATENCY_MS_VALUE:-1000}"
SIM_OPERATIONAL_SLO_MAX_SUMMARY_LATENCY_MS_VALUE="${SIM_OPERATIONAL_SLO_MAX_SUMMARY_LATENCY_MS:-$(existing_value SIM_OPERATIONAL_SLO_MAX_SUMMARY_LATENCY_MS)}"
SIM_OPERATIONAL_SLO_MAX_SUMMARY_LATENCY_MS_VALUE="${SIM_OPERATIONAL_SLO_MAX_SUMMARY_LATENCY_MS_VALUE:-3000}"
SIM_OPERATIONAL_SLO_MAX_TOTAL_DURATION_MS_VALUE="${SIM_OPERATIONAL_SLO_MAX_TOTAL_DURATION_MS:-$(existing_value SIM_OPERATIONAL_SLO_MAX_TOTAL_DURATION_MS)}"
SIM_OPERATIONAL_SLO_MAX_TOTAL_DURATION_MS_VALUE="${SIM_OPERATIONAL_SLO_MAX_TOTAL_DURATION_MS_VALUE:-180000}"
SIM_OPERATIONAL_SLO_REQUIRE_OPERATIONS_OK_VALUE="${SIM_OPERATIONAL_SLO_REQUIRE_OPERATIONS_OK:-$(existing_value SIM_OPERATIONAL_SLO_REQUIRE_OPERATIONS_OK)}"
SIM_OPERATIONAL_SLO_REQUIRE_OPERATIONS_OK_VALUE="${SIM_OPERATIONAL_SLO_REQUIRE_OPERATIONS_OK_VALUE:-true}"
SIM_OPERATIONS_PROVIDER_TIMEOUT_MS_VALUE="${SIM_OPERATIONS_PROVIDER_TIMEOUT_MS:-$(existing_value SIM_OPERATIONS_PROVIDER_TIMEOUT_MS)}"
SIM_OPERATIONS_PROVIDER_TIMEOUT_MS_VALUE="${SIM_OPERATIONS_PROVIDER_TIMEOUT_MS_VALUE:-1500}"
SIM_OPERATIONS_FLIGHT_DATA_BASE_URL_VALUE="${SIM_OPERATIONS_FLIGHT_DATA_BASE_URL:-$(existing_value SIM_OPERATIONS_FLIGHT_DATA_BASE_URL)}"
SIM_OPERATIONS_FLIGHT_DATA_BASE_URL_VALUE="${SIM_OPERATIONS_FLIGHT_DATA_BASE_URL_VALUE:-http://flight-data-api:4010}"
SIM_OPERATIONS_SITUATION_DATA_BASE_URL_VALUE="${SIM_OPERATIONS_SITUATION_DATA_BASE_URL:-$(existing_value SIM_OPERATIONS_SITUATION_DATA_BASE_URL)}"
SIM_OPERATIONS_SITUATION_DATA_BASE_URL_VALUE="${SIM_OPERATIONS_SITUATION_DATA_BASE_URL_VALUE:-http://situation-data-api:4020}"
SIM_OPERATIONS_SAFETY_DATA_BASE_URL_VALUE="${SIM_OPERATIONS_SAFETY_DATA_BASE_URL:-$(existing_value SIM_OPERATIONS_SAFETY_DATA_BASE_URL)}"
SIM_OPERATIONS_SAFETY_DATA_BASE_URL_VALUE="${SIM_OPERATIONS_SAFETY_DATA_BASE_URL_VALUE:-http://safety-data-api:4030}"
SIM_OPERATIONS_TAK_GATEWAY_BASE_URL_VALUE="${SIM_OPERATIONS_TAK_GATEWAY_BASE_URL:-$(existing_value SIM_OPERATIONS_TAK_GATEWAY_BASE_URL)}"
SIM_OPERATIONS_TAK_GATEWAY_BASE_URL_VALUE="${SIM_OPERATIONS_TAK_GATEWAY_BASE_URL_VALUE:-http://tak-gateway-api:4040}"
SIM_OPERATIONS_REPORT_FILE_VALUE="${SIM_OPERATIONS_REPORT_FILE:-$(existing_value SIM_OPERATIONS_REPORT_FILE)}"
SIM_OPERATIONS_REPORT_FILE_VALUE="${SIM_OPERATIONS_REPORT_FILE_VALUE:-/data/operational-checks/latest.json}"
SITUATION_DATA_CHMI_WEATHER_MAX_STATIONS_VALUE="${SITUATION_DATA_CHMI_WEATHER_MAX_STATIONS:-$(existing_value SITUATION_DATA_CHMI_WEATHER_MAX_STATIONS)}"
SITUATION_DATA_CHMI_WEATHER_MAX_STATIONS_VALUE="${SITUATION_DATA_CHMI_WEATHER_MAX_STATIONS_VALUE:-600}"

umask 077
cat > .env <<ENV
SIM_WEB_PORT=5020
API_PORT=4000
SIM_PUBLISHER_MODE=DRY_RUN
SIM_SOURCE_SYSTEM_ID=sim-air-situation-001
SIM_ADAPTER_VERSION=0.1.0
SIM_DATA_DIR=/data
MAIN_COP_BASE_URL=http://sim-api:4000/mock-cop
MAIN_COP_BEARER_TOKEN=dev-lab-token
EXTERNAL_AI_ALLOWED=false
SIM_API_AUTH_REQUIRED=true
SIM_API_PUBLIC_READ=false
SIM_API_AUTH_MODE=hybrid
SIM_API_ADMIN_TOKEN=${SIM_API_ADMIN_TOKEN_VALUE}
SIM_API_INTERNAL_TOKEN=
SIM_API_TOKENS=
SIM_OIDC_ISSUER=https://login.zeleznalady.cz/realms/cop
SIM_OIDC_JWKS_URI=http://docker.home.cz:8081/realms/cop/protocol/openid-connect/certs
SIM_OIDC_CLIENT_ID=csm-sim-web
SIM_OIDC_ALLOWED_CLIENTS=csm-sim-web
VITE_SIM_AUTH_MODE=hybrid
VITE_SIM_OIDC_ISSUER=https://login.zeleznalady.cz/realms/cop
VITE_SIM_OIDC_CLIENT_ID=csm-sim-web
VITE_SIM_OIDC_SCOPE=openid profile email
VITE_SIM_PUBLIC_READ_ENABLED=false
VITE_SIM_ALLOW_TOKEN_LOGIN=false
SIM_API_CORS_ORIGINS=
SIM_API_RATE_LIMIT_WINDOW_MS=60000
SIM_API_RATE_LIMIT_MAX_REQUESTS=300
SIM_OPERATIONS_PROVIDER_TIMEOUT_MS=${SIM_OPERATIONS_PROVIDER_TIMEOUT_MS_VALUE}
SIM_OPERATIONS_FLIGHT_DATA_BASE_URL=${SIM_OPERATIONS_FLIGHT_DATA_BASE_URL_VALUE}
SIM_OPERATIONS_SITUATION_DATA_BASE_URL=${SIM_OPERATIONS_SITUATION_DATA_BASE_URL_VALUE}
SIM_OPERATIONS_SAFETY_DATA_BASE_URL=${SIM_OPERATIONS_SAFETY_DATA_BASE_URL_VALUE}
SIM_OPERATIONS_TAK_GATEWAY_BASE_URL=${SIM_OPERATIONS_TAK_GATEWAY_BASE_URL_VALUE}
SIM_OPERATIONS_REPORT_FILE=${SIM_OPERATIONS_REPORT_FILE_VALUE}
SIM_SCENARIO_MAX_BLOCKS=24
SIM_SCENARIO_MAX_ACTIVE_OBJECTS=1000
SIM_SCENARIO_MAX_EVENTS_PER_SECOND=1000
FLIGHT_DATA_ENABLED_SOURCES=adsb_lol
FLIGHT_DATA_DEFAULT_LAT=50.1008
FLIGHT_DATA_DEFAULT_LON=14.2632
FLIGHT_DATA_DEFAULT_RADIUS_NM=120
FLIGHT_DATA_CACHE_TTL_SECONDS=10
FLIGHT_DATA_STALE_IF_ERROR_SECONDS=60
FLIGHT_DATA_CACHE_MAX_ENTRIES=512
FLIGHT_DATA_STALE_AFTER_SECONDS=120
FLIGHT_DATA_CORS_ORIGINS=
FLIGHT_DATA_REQUEST_TIMEOUT_MS=8000
LOCAL_ADSB_AIRCRAFT_JSON_URLS=
OURAIRPORTS_ENABLED=true
OURAIRPORTS_COUNTRIES=CZ,SK,AT,DE,PL,HU
OURAIRPORTS_CACHE_TTL_SECONDS=86400
SITUATION_DATA_ENABLED_SOURCES=open_meteo,aviation_weather,chmi_weather_stations,chmi_air_quality,osm_postgis,mobile_coverage_model,mobile_network_model,ctu_nettest,ctu_stationary_mobile,pid_gtfs_rt,road_srti_lod,safety_data
SITUATION_DATA_DEFAULT_BBOX=13.85,49.65,15.35,50.45
SITUATION_DATA_CACHE_TTL_SECONDS=30
SITUATION_DATA_STALE_IF_ERROR_SECONDS=1800
SITUATION_DATA_CACHE_MAX_ENTRIES=10000
SITUATION_DATA_BBOX_CACHE_PADDING_DEGREES=0.18
SITUATION_DATA_OPEN_METEO_CACHE_TTL_SECONDS=600
SITUATION_DATA_OPEN_METEO_GRID_DEGREES=0.05
SITUATION_DATA_OSM_POSTGIS_CACHE_TTL_SECONDS=21600
SITUATION_DATA_OVERPASS_CACHE_TTL_SECONDS=21600
SITUATION_DATA_SAFETY_CACHE_TTL_SECONDS=300
SITUATION_DATA_AVIATION_WEATHER_CACHE_TTL_SECONDS=600
SITUATION_DATA_CHMI_WEATHER_MAX_STATIONS=${SITUATION_DATA_CHMI_WEATHER_MAX_STATIONS_VALUE}
IDSJMK_VEHICLE_POSITIONS_URL=https://mapa.idsjmk.cz/api/vehicles.json
SITUATION_DATA_IDSJMK_CACHE_TTL_SECONDS=20
ROAD_SRTI_LOD_SPARQL_URL=https://lod.tamtamresearch.com/sparql/
SITUATION_DATA_ROAD_SRTI_CACHE_TTL_SECONDS=300
ROAD_SRTI_LOD_MAX_RECORDS=1500
SITUATION_DATA_ARDOS_CACHE_TTL_SECONDS=15
SITUATION_DATA_MOBILE_NETWORK_CACHE_TTL_SECONDS=3600
SITUATION_DATA_MOBILE_COVERAGE_CACHE_TTL_SECONDS=21600
MOBILE_COVERAGE_RESOLUTION_M=1000
MOBILE_COVERAGE_MAX_CELLS=1000
MOBILE_COVERAGE_MODEL_VERSION=${MOBILE_COVERAGE_MODEL_VERSION_VALUE}
MOBILE_COVERAGE_DEM_SOURCE=${MOBILE_COVERAGE_DEM_SOURCE_VALUE}
MOBILE_COVERAGE_TERRAIN_AWARE=${MOBILE_COVERAGE_TERRAIN_AWARE_VALUE}
MOBILE_COVERAGE_DEFAULT_ANTENNA_HEIGHT_M=30
MOBILE_COVERAGE_READ_MODEL_ENABLED=true
MOBILE_COVERAGE_READ_MODEL_TABLE=public.mobile_coverage_cells
MOBILE_COVERAGE_READ_MODEL_MAX_AGE_SECONDS=604800
DEM_ENABLED=${DEM_ENABLED_VALUE}
DEM_BBOX=${DEM_BBOX_VALUE}
DEM_DATASET_ID=${DEM_DATASET_ID_VALUE}
DEM_POSTGIS_DATABASE_URL=${DEM_POSTGIS_DATABASE_URL_VALUE}
DEM_LOCAL_CACHE_HOST_DIR=${DEM_LOCAL_CACHE_HOST_DIR_VALUE}
DEM_LOCAL_CACHE_DIR=${DEM_LOCAL_CACHE_DIR_VALUE}
DEM_SEAWEEDFS_ENABLED=${DEM_SEAWEEDFS_ENABLED_VALUE}
DEM_SEAWEEDFS_S3_ENDPOINT=${DEM_SEAWEEDFS_S3_ENDPOINT_VALUE}
DEM_SEAWEEDFS_BUCKET=${DEM_SEAWEEDFS_BUCKET_VALUE}
DEM_SEAWEEDFS_PREFIX=${DEM_SEAWEEDFS_PREFIX_VALUE}
DEM_SEAWEEDFS_ACCESS_KEY_ID=${DEM_SEAWEEDFS_ACCESS_KEY_ID_VALUE}
DEM_SEAWEEDFS_SECRET_ACCESS_KEY=${DEM_SEAWEEDFS_SECRET_ACCESS_KEY_VALUE}
SIM_OPERATIONAL_ALERT_WEBHOOK_URL=${SIM_OPERATIONAL_ALERT_WEBHOOK_URL_VALUE}
SIM_OPERATIONAL_ALERT_ENVIRONMENT=${SIM_OPERATIONAL_ALERT_ENVIRONMENT_VALUE}
SIM_OPERATIONAL_BASE_URL=${SIM_OPERATIONAL_BASE_URL_VALUE}
SIM_OPERATIONAL_API_TOKEN=${SIM_OPERATIONAL_API_TOKEN_VALUE}
SIM_OPERATIONAL_CHECK_BBOX=${SIM_OPERATIONAL_CHECK_BBOX_VALUE}
SIM_OPERATIONAL_BOUNDARY_BBOX=${SIM_OPERATIONAL_BOUNDARY_BBOX_VALUE}
SIM_OPERATIONAL_TERRAIN_BBOX=${SIM_OPERATIONAL_TERRAIN_BBOX_VALUE}
SIM_OPERATIONAL_EXPECTED_DEM_SOURCE=${SIM_OPERATIONAL_EXPECTED_DEM_SOURCE_VALUE}
SIM_OPERATIONAL_EXPECTED_MOBILE_MODEL_VERSION=${SIM_OPERATIONAL_EXPECTED_MOBILE_MODEL_VERSION_VALUE}
SIM_OPERATIONAL_REQUIRE_DEM=${SIM_OPERATIONAL_REQUIRE_DEM_VALUE}
SIM_OPERATIONAL_REQUIRE_TERRAIN_AWARE=${SIM_OPERATIONAL_REQUIRE_TERRAIN_AWARE_VALUE}
SIM_OPERATIONAL_ALERT_ON_RECOVERY=${SIM_OPERATIONAL_ALERT_ON_RECOVERY_VALUE}
SIM_OPERATIONAL_ALERT_EVERY_FAILURE=${SIM_OPERATIONAL_ALERT_EVERY_FAILURE_VALUE}
SIM_OPERATIONAL_SLO_AVAILABILITY_TARGET=${SIM_OPERATIONAL_SLO_AVAILABILITY_TARGET_VALUE}
SIM_OPERATIONAL_CHECK_INTERVAL_SECONDS=${SIM_OPERATIONAL_CHECK_INTERVAL_SECONDS_VALUE}
SIM_OPERATIONAL_SLO_MAX_LIVE_LATENCY_MS=${SIM_OPERATIONAL_SLO_MAX_LIVE_LATENCY_MS_VALUE}
SIM_OPERATIONAL_SLO_MAX_SUMMARY_LATENCY_MS=${SIM_OPERATIONAL_SLO_MAX_SUMMARY_LATENCY_MS_VALUE}
SIM_OPERATIONAL_SLO_MAX_TOTAL_DURATION_MS=${SIM_OPERATIONAL_SLO_MAX_TOTAL_DURATION_MS_VALUE}
SIM_OPERATIONAL_SLO_REQUIRE_OPERATIONS_OK=${SIM_OPERATIONAL_SLO_REQUIRE_OPERATIONS_OK_VALUE}
SITUATION_DATA_STALE_AFTER_SECONDS=900
SITUATION_DATA_REQUEST_TIMEOUT_MS=8000
OPEN_METEO_BASE_URL=https://api.open-meteo.com
OSM_POSTGIS_DB=${OSM_POSTGIS_DB_VALUE}
OSM_POSTGIS_USER=${OSM_POSTGIS_USER_VALUE}
OSM_POSTGIS_PASSWORD=${OSM_POSTGIS_PASSWORD_VALUE}
OSM_POSTGIS_BACKEND=${OSM_POSTGIS_BACKEND_VALUE}
OSM_POSTGIS_DATABASE_URL=${OSM_POSTGIS_DATABASE_URL_VALUE}
OSM_POSTGIS_TABLE=${OSM_POSTGIS_TABLE_VALUE}
OSM_POSTGIS_ADMIN_BOUNDARY_TABLE=${OSM_POSTGIS_ADMIN_BOUNDARY_TABLE_VALUE}
OVERPASS_BASE_URL=https://overpass-api.de/api/interpreter
OVERPASS_MAX_BBOX_DEGREES=1.6
CTU_NETTEST_URL=https://nettest.ctu.gov.cz/RMBTStatisticServer/export/nettest-opendata_hours-048.zip
PID_GTFS_RT_VEHICLE_POSITIONS_URL=https://api.golemio.cz/v2/vehiclepositions/gtfsrt/vehicle_positions.pb
SAFETY_DATA_BASE_URL=http://safety-data-api:4030
SAFETY_DATA_ENABLED_SOURCES=chmi_alerts,chmi_hydro,admin_boundaries
CHMI_ORP_CODELIST_URL=https://apl2.czso.cz/iSMS/do_cis_export?cisjaz=203&cisvaz=61_88&format=2&kodcis=65&separator=,&typdat=1
SAFETY_DATA_ADMIN_BOUNDARY_DATABASE_URL=${SAFETY_DATA_ADMIN_BOUNDARY_DATABASE_URL_VALUE}
SAFETY_DATA_ADMIN_BOUNDARY_TABLE=${SAFETY_DATA_ADMIN_BOUNDARY_TABLE_VALUE}
SAFETY_DATA_ADMIN_BOUNDARY_CACHE_TTL_SECONDS=${SAFETY_DATA_ADMIN_BOUNDARY_CACHE_TTL_SECONDS_VALUE}
NASA_FIRMS_MAP_KEY=
NASA_FIRMS_AREA_BASE_URL=https://firms.modaps.eosdis.nasa.gov/api/area/csv
NASA_FIRMS_SOURCE=VIIRS_SNPP_NRT
NASA_FIRMS_DAY_RANGE=1
AVIATION_WEATHER_BASE_URL=https://aviationweather.gov
ARDOS_PARTNER_BASE_URL=
ARDOS_PARTNER_TOKEN=
SITUATION_DATA_CORS_ORIGINS=
TAK_GATEWAY_INGEST_TOKEN=dev-tak-ingest-token
TAK_GATEWAY_READ_TOKEN=
TAK_GATEWAY_PUBLIC_READ=false
TAK_GATEWAY_DEFAULT_BBOX=11.8,48.5,19.2,51.2
TAK_GATEWAY_STALE_AFTER_SECONDS=300
TAK_GATEWAY_RETENTION_SECONDS=3600
TAK_GATEWAY_MAX_EVENTS=5000
TAK_GATEWAY_EXPOSE_RAW=false
TAK_GATEWAY_SOURCE_LABEL=TAK/CoT gateway
TAK_GATEWAY_CORS_ORIGINS=
SAFETY_DATA_CORS_ORIGINS=
ENV

docker compose up -d --build
docker compose ps
wait_for_container_healthy csm-sim-web "sim-web container health"
wait_for_http http://localhost:5020/health/live "sim-web gateway"
curl -fsS http://localhost:5020/health/live
curl -fsS -H "Authorization: Bearer ${SIM_API_ADMIN_TOKEN_VALUE}" http://localhost:5020/api/v1/operations/summary >/dev/null
curl -fsS -H "Authorization: Bearer ${SIM_API_ADMIN_TOKEN_VALUE}" 'http://localhost:5020/api/v1/operations/provider-details?includeDetails=true&includeObservability=true' >/dev/null
curl -fsS -H "Authorization: Bearer ${SIM_API_ADMIN_TOKEN_VALUE}" http://localhost:5020/api/v1/scenarios >/dev/null
curl -fsS http://localhost:5020/flight-data/health/ready
curl -fsS http://localhost:5020/situation-data/health/ready
curl -fsS http://localhost:5020/safety-data/health/ready
curl -fsS http://localhost:5020/tak-gateway/health/ready
curl -fsS http://localhost:5020/situation-data/api/v1/catalog >/dev/null
curl -fsS http://localhost:5020/safety-data/api/v1/catalog >/dev/null
curl -fsS http://localhost:5020/situation-data/api/v1/taxonomy >/dev/null
curl -fsS http://localhost:5020/safety-data/api/v1/taxonomy >/dev/null
curl -fsS 'http://localhost:5020/situation-data/api/v1/features/summary?limit=1' >/dev/null
curl -fsS 'http://localhost:5020/safety-data/api/v1/features/summary?limit=1' >/dev/null
curl -fsS 'http://localhost:5020/situation-data/api/v1/features?layers=weather,mobile_network,traffic,warnings,flood&limit=20' >/dev/null
python3 scripts/smoke-provider-gateway.py --base-url http://localhost:5020 --allow-degraded-health situation --allow-degraded-health tak --quiet
python3 scripts/smoke-production-data-plane.py --base-url http://localhost:5020 --quiet
test "$(curl -sS -o /dev/null -w '%{http_code}' http://localhost:5020/metrics)" = "404"
echo "SIM API admin token is stored in /srv/sim/.env as SIM_API_ADMIN_TOKEN."
