#!/usr/bin/env bash
set -euo pipefail

cd /srv/sim

if [ ! -d .git ]; then
  : "${SIM_GIT_REPOSITORY_URL:?Set SIM_GIT_REPOSITORY_URL to the SIM repository clone URL.}"
  git clone "$SIM_GIT_REPOSITORY_URL" .
else
  git pull --ff-only
fi

existing_value() {
  local key="$1"
  if [ -f .env ]; then
    grep -E "^${key}=" .env | tail -n 1 | cut -d= -f2- || true
  fi
}

generate_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    python3 - <<'PY'
import secrets
print(secrets.token_hex(32))
PY
  fi
}

SIM_API_ADMIN_TOKEN_VALUE="${SIM_API_ADMIN_TOKEN:-$(existing_value SIM_API_ADMIN_TOKEN)}"
if [ -z "$SIM_API_ADMIN_TOKEN_VALUE" ]; then
  SIM_API_ADMIN_TOKEN_VALUE="$(generate_secret)"
fi

umask 077
cat > .env <<ENV
SIM_WEB_PORT=5020
API_PORT=4000
SIM_PUBLISHER_MODE=DRY_RUN
SIM_SOURCE_SYSTEM_ID=sim-air-situation-001
SIM_ADAPTER_VERSION=0.1.0
SIM_DATA_DIR=/data
MAIN_COP_BASE_URL=http://sim-api:4000/mock-cop
MAIN_COP_BEARER_TOKEN=dev-lab-token
EXTERNAL_AI_ALLOWED=false
SIM_API_AUTH_REQUIRED=true
SIM_API_PUBLIC_READ=true
SIM_API_AUTH_MODE=hybrid
SIM_API_ADMIN_TOKEN=${SIM_API_ADMIN_TOKEN_VALUE}
SIM_API_INTERNAL_TOKEN=
SIM_API_TOKENS=
SIM_OIDC_ISSUER=https://login.zeleznalady.cz/realms/cop
SIM_OIDC_JWKS_URI=
SIM_OIDC_CLIENT_ID=csm-sim-web
SIM_OIDC_ALLOWED_CLIENTS=csm-sim-web
VITE_SIM_AUTH_MODE=hybrid
VITE_SIM_OIDC_ISSUER=https://login.zeleznalady.cz/realms/cop
VITE_SIM_OIDC_CLIENT_ID=csm-sim-web
VITE_SIM_OIDC_SCOPE=openid profile email
SIM_API_CORS_ORIGINS=
SIM_API_RATE_LIMIT_WINDOW_MS=60000
SIM_API_RATE_LIMIT_MAX_REQUESTS=300
SIM_SCENARIO_MAX_BLOCKS=24
SIM_SCENARIO_MAX_ACTIVE_OBJECTS=1000
SIM_SCENARIO_MAX_EVENTS_PER_SECOND=1000
FLIGHT_DATA_ENABLED_SOURCES=adsb_lol
FLIGHT_DATA_DEFAULT_LAT=50.1008
FLIGHT_DATA_DEFAULT_LON=14.2632
FLIGHT_DATA_DEFAULT_RADIUS_NM=120
FLIGHT_DATA_CACHE_TTL_SECONDS=10
FLIGHT_DATA_STALE_IF_ERROR_SECONDS=60
FLIGHT_DATA_CACHE_MAX_ENTRIES=512
FLIGHT_DATA_STALE_AFTER_SECONDS=120
FLIGHT_DATA_CORS_ORIGINS=
FLIGHT_DATA_REQUEST_TIMEOUT_MS=8000
LOCAL_ADSB_AIRCRAFT_JSON_URLS=
OURAIRPORTS_ENABLED=true
OURAIRPORTS_COUNTRIES=CZ,SK,AT,DE,PL,HU
OURAIRPORTS_CACHE_TTL_SECONDS=86400
SITUATION_DATA_ENABLED_SOURCES=open_meteo,aviation_weather,osm_postgis,mobile_coverage_model,mobile_network_model,ctu_nettest,pid_gtfs_rt,safety_data
SITUATION_DATA_DEFAULT_BBOX=13.85,49.65,15.35,50.45
SITUATION_DATA_CACHE_TTL_SECONDS=30
SITUATION_DATA_STALE_IF_ERROR_SECONDS=1800
SITUATION_DATA_CACHE_MAX_ENTRIES=10000
SITUATION_DATA_BBOX_CACHE_PADDING_DEGREES=0.18
SITUATION_DATA_OPEN_METEO_CACHE_TTL_SECONDS=600
SITUATION_DATA_OPEN_METEO_GRID_DEGREES=0.05
SITUATION_DATA_OSM_POSTGIS_CACHE_TTL_SECONDS=21600
SITUATION_DATA_OVERPASS_CACHE_TTL_SECONDS=21600
SITUATION_DATA_SAFETY_CACHE_TTL_SECONDS=300
SITUATION_DATA_AVIATION_WEATHER_CACHE_TTL_SECONDS=600
SITUATION_DATA_ARDOS_CACHE_TTL_SECONDS=15
SITUATION_DATA_MOBILE_NETWORK_CACHE_TTL_SECONDS=3600
SITUATION_DATA_MOBILE_COVERAGE_CACHE_TTL_SECONDS=21600
MOBILE_COVERAGE_RESOLUTION_M=1000
MOBILE_COVERAGE_MAX_CELLS=1000
MOBILE_COVERAGE_MODEL_VERSION=coverage-v1
MOBILE_COVERAGE_DEM_SOURCE=not-used-phase-1
MOBILE_COVERAGE_TERRAIN_AWARE=false
MOBILE_COVERAGE_DEFAULT_ANTENNA_HEIGHT_M=30
DEM_ENABLED=false
DEM_BBOX=11.8,48.5,19.2,51.2
DEM_DATASET_ID=copernicus-glo30-cz
DEM_POSTGIS_DATABASE_URL=
DEM_LOCAL_CACHE_HOST_DIR=./data/dem-cache/copernicus-glo30
DEM_LOCAL_CACHE_DIR=/dem-cache/copernicus-glo30
DEM_SEAWEEDFS_ENABLED=false
DEM_SEAWEEDFS_S3_ENDPOINT=
DEM_SEAWEEDFS_BUCKET=sim-dem
DEM_SEAWEEDFS_PREFIX=copernicus-glo30/2021
DEM_SEAWEEDFS_ACCESS_KEY_ID=
DEM_SEAWEEDFS_SECRET_ACCESS_KEY=
SITUATION_DATA_STALE_AFTER_SECONDS=900
SITUATION_DATA_REQUEST_TIMEOUT_MS=8000
OPEN_METEO_BASE_URL=https://api.open-meteo.com
OSM_POSTGIS_DB=sim_osm
OSM_POSTGIS_USER=sim_osm
OSM_POSTGIS_PASSWORD=
OSM_POSTGIS_BACKEND=
OSM_POSTGIS_DATABASE_URL=
OSM_POSTGIS_TABLE=public.osm_poi
OVERPASS_BASE_URL=https://overpass-api.de/api/interpreter
OVERPASS_MAX_BBOX_DEGREES=1.6
CTU_NETTEST_URL=https://nettest.ctu.gov.cz/RMBTStatisticServer/export/nettest-opendata_hours-048.zip
PID_GTFS_RT_VEHICLE_POSITIONS_URL=https://api.golemio.cz/v2/vehiclepositions/gtfsrt/vehicle_positions.pb
SAFETY_DATA_BASE_URL=http://safety-data-api:4030
AVIATION_WEATHER_BASE_URL=https://aviationweather.gov
ARDOS_PARTNER_BASE_URL=
ARDOS_PARTNER_TOKEN=
SITUATION_DATA_CORS_ORIGINS=
TAK_GATEWAY_INGEST_TOKEN=dev-tak-ingest-token
TAK_GATEWAY_READ_TOKEN=
TAK_GATEWAY_PUBLIC_READ=false
TAK_GATEWAY_DEFAULT_BBOX=11.8,48.5,19.2,51.2
TAK_GATEWAY_STALE_AFTER_SECONDS=300
TAK_GATEWAY_RETENTION_SECONDS=3600
TAK_GATEWAY_MAX_EVENTS=5000
TAK_GATEWAY_EXPOSE_RAW=false
TAK_GATEWAY_SOURCE_LABEL=TAK/CoT gateway
TAK_GATEWAY_CORS_ORIGINS=
SAFETY_DATA_CORS_ORIGINS=
ENV

docker compose up -d --build
docker compose ps
curl -fsS http://localhost:5020/health/live
curl -fsS -H "Authorization: Bearer ${SIM_API_ADMIN_TOKEN_VALUE}" http://localhost:5020/api/v1/scenarios >/dev/null
curl -fsS http://localhost:5020/flight-data/health/ready
curl -fsS http://localhost:5020/situation-data/health/ready
curl -fsS http://localhost:5020/tak-gateway/health/ready
curl -fsS http://localhost:5020/situation-data/api/v1/catalog >/dev/null
curl -fsS 'http://localhost:5020/situation-data/api/v1/features?layers=weather,mobile_network,traffic,warnings,flood&limit=20' >/dev/null
test "$(curl -sS -o /dev/null -w '%{http_code}' http://localhost:5020/metrics)" = "404"
echo "SIM API admin token is stored in /srv/sim/.env as SIM_API_ADMIN_TOKEN."
